version: "3"

services:
    web:
        image: nginx:alpine
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: .
        volumes:
            - ${APPLICATION}:/var/www/html
        environment:
            DB_USER: ${MYSQL_USER}
            DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_data:/var/lib/mysql"
            - "./mysql/initial_data:/docker-entrypoint-initdb.d"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
    db_data:
