version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APPLICATION}:/app
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    restart: always
    build:
      context: .
      args:
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
    volumes:
      - ${APPLICATION}:/app
    # environment:
    #   XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1

  composer:
    image: composer/composer:alpine
    command: install
    volumes:
      - ${APPLICATION}:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
