version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  php:
    build: .
    volumes:
      - ./app:/app
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge