version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APPLICATION}:/app
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .
      args:
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
    volumes:
      - ${APPLICATION}:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

volumes:
  db_data:
