version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APPLICATION}:/app
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    volumes:
      - ${APPLICATION}:/app
    environment:
      DB_USER: ${MYSQL_USER}
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

volumes:
  db_data:
