version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APPLICATION}:/app
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ${APPLICATION}:/app

  composer:
    image: composer/composer:alpine
    command: install
    volumes:
      - ${APPLICATION}:/app
