version: "3"

services:
    web:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: .
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
